/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'SUTHIP' at '6/9/18 10:10 AM' with Gradle 2.14.1
 *
 * @author SUTHIP, @date 6/9/18 10:10 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
